# <font size=6>**TECH CHALLENGE FASE 1: Case NPS Preditivo**</font>

# **I. 📊 Tech Challenge – Fase 1**

## **Introdução**

Estamos atuando como cientistas de dados em uma empresa de e-commerce que vem enfrentando desafios relacionados à experiência do cliente.

Com o crescimento acelerado das operações, a empresa passou a lidar com um aumento significativo no volume de pedidos, entregas e interações com clientes. Apesar dos ganhos de escala, observou-se uma grande variabilidade no nível de satisfação dos consumidores, medida pelo Net Promoter Score (NPS).

O principal desafio de negócio consiste em entender:

- Quais fatores operacionais impactam a satisfação do cliente;
- Por que clientes com experiências semelhantes apresentam percepções distintas;
- Como antecipar a insatisfação antes mesmo da coleta do NPS.

Neste contexto, nosso papel é transformar dados operacionais — como informações de pedidos, logística e atendimento — em insights acionáveis que apoiem a tomada de decisão das áreas de negócio.

Ao longo deste projeto, iremos:
- Explorar os dados disponíveis;
- Identificar padrões de comportamento dos clientes;
- Gerar insights relevantes para o negócio;
- E propor, opcionalmente, uma abordagem preditiva para antecipação do NPS.

O foco principal não será apenas a análise técnica, mas a capacidade de traduzir dados em recomendações estratégicas claras e aplicáveis.

## **1. 🧠 Entendimento do Negócio**

### 📍 Qual problema de negócio está sendo resolvido?

A empresa enfrenta um desafio relacionado à variabilidade na satisfação dos clientes, medida pelo Net Promoter Score (NPS). Mesmo quando os indicadores operacionais são semelhantes, como tempo de entrega ou número de contatos com o atendimento, diferentes clientes apresentam percepções distintas sobre a experiência de compra.

O principal problema de negócio consiste em identificar quais fatores realmente influenciam a satisfação do cliente e como a empresa pode atuar de forma proativa para melhorar essa experiência antes da coleta do NPS.

Atualmente, o NPS é mensurado apenas ao final da jornada, o que limita a capacidade da empresa de antecipar problemas e agir preventivamente. Dessa forma, há uma necessidade clara de transformar dados operacionais em insights acionáveis.

---

### ⭐ Por que o NPS é importante para um e-commerce?

O Net Promoter Score (NPS) é um dos principais indicadores de experiência do cliente, pois mede a probabilidade de um consumidor recomendar a empresa para outras pessoas, ou ser seu detrator.

No contexto de e-commerce, o NPS é especialmente relevante porque:

- Reflete a qualidade da experiência de ponta a ponta (compra, entrega e pós-venda);
- Está diretamente associado à fidelização do cliente;
- Influencia a reputação da marca em ambientes digitais;
- Permite identificar rapidamente problemas operacionais que impactam o cliente.

Além disso, o NPS sintetiza múltiplas dimensões da experiência em um único indicador, facilitando o acompanhamento estratégico.

---

### 🏢 Quais áreas podem se beneficiar desses insights?

Os insights gerados a partir da análise do NPS podem apoiar diversas áreas da empresa:

- **Logística**: otimização de prazos de entrega, redução de atrasos e tentativas de entrega;
- **Atendimento ao cliente**: melhoria no tempo de resposta e resolução de problemas;
- **Produto**: identificação de falhas na experiência de compra ou qualidade dos itens;
- **Pricing**: avaliação do impacto de preços e descontos na percepção do cliente;
- **Estratégia**: definição de prioridades para melhoria da experiência do cliente.

---

### 🔄 Como o NPS impacta o negócio?

#### 📌 Recompra
Clientes satisfeitos (promotores) têm maior probabilidade de realizar novas compras, aumentando o lifetime value (LTV) e reduzindo custos de aquisição.

#### 📌 Boca a boca
O NPS está diretamente relacionado ao marketing orgânico. Promotores tendem a recomendar a marca, enquanto detratores podem gerar impacto negativo na reputação.

#### 📌 Market share
Empresas com maior nível de satisfação tendem a ganhar participação de mercado, especialmente em ambientes digitais altamente competitivos, como o e-commerce.

---

### 📊 Indicadores que podem complementar a análise

Para uma visão mais completa, o NPS pode ser analisado em conjunto com outros indicadores:

- **Benchmarks de NPS do mercado**: para avaliar o posicionamento da empresa frente aos concorrentes;
- **SLA logístico**: tempo médio de entrega, taxa de atraso e eficiência operacional;
- **Taxa de recompra**: indicador direto de fidelização;
- **Indicadores de atendimento**: tempo de resposta e resolução;
- **Dados da concorrência**: percepção de valor e experiência comparativa.

---

### 🎯 Papel da Ciência de Dados

Neste contexto, a Ciência de Dados atua como um elo entre dados operacionais e tomada de decisão estratégica, permitindo:

- Identificar padrões de comportamento dos clientes;
- Antecipar riscos de insatisfação;
- Priorizar ações com maior impacto no NPS;
- Apoiar decisões orientadas por dados em toda a organização.

## **2. 🎯 Definição da Target**

### 📌 Qual variável representa a satisfação do cliente?

A variável que representa a satisfação do cliente neste contexto é a **`nps_score`**, que varia de 0 a 10 e reflete a percepção do cliente após sua experiência de compra.

---

### 📌 Por que essa variável foi escolhida?

O **NPS (Net Promoter Score)** foi escolhido por ser um dos principais indicadores de experiência do cliente utilizados no mercado, permitindo classificar os consumidores em três grupos, conforme se pode visualizar abaixo:

![Definição de NPS](https://lh3.googleusercontent.com/d/1Za8FZy-dDOTnYECG2WVnDXxD2k08bpNk)

- **Promotores (nota 9-10)**: clientes satisfeitos e propensos a recomendar a marca;
- **Passivos ou Neutros (nota 7-8)**: clientes com experiência razoável, mas sem forte engajamento;
- **Detratores (nota 0-6)**: clientes insatisfeitos, com potencial impacto negativo na reputação.

Inclusive, o NPS sintetiza a experiência do cliente de ponta a ponta: incluindo compra, entrega e atendimento, tornando-se um indicador estratégico para o negócio.

---

### 📌 Em que momento da jornada essa informação é coletada?

O `nps_score` é coletado **ao final da jornada de compra**, após a entrega do pedido e a consolidação da experiência do cliente.

Isso significa que ele reflete uma avaliação retrospectiva, baseada em toda a interação do cliente com a empresa.

---

### ⚠️ Existe algum risco no uso dessa variável?

Sim, existem alguns riscos importantes que devem ser considerados:

- **Visão tardia da experiência**: como o NPS é coletado apenas no final da jornada, ele não permite ação preventiva direta durante a experiência do cliente;
  
- **Viés de resposta**: nem todos os clientes respondem à pesquisa, podendo gerar distorções na análise (ex: clientes muito satisfeitos ou muito insatisfeitos tendem a responder mais);

- **Simplificação excessiva**: apesar de útil, o NPS resume a experiência em uma única nota, podendo ocultar nuances importantes;

- **Uso como única métrica**: decisões baseadas exclusivamente no NPS podem ignorar outros indicadores relevantes, como tempo de entrega ou qualidade do atendimento.

---

### 🎯 Implicação para o projeto

Diante desses pontos, o principal objetivo da análise será utilizar variáveis operacionais (logística, atendimento, pedido) para **explicar e antecipar o comportamento do NPS**, permitindo que a empresa atue de forma mais proativa na gestão da experiência do cliente.

# **II. 📁 Entendendo os dados - Entendendo os dados**

---

## 📦 2.1 Importando os pacotes e lendo os dados

## 🛠️ Bibliotecas Utilizadas

Para a análise dos dados e geração de insights, utilizaremos as principais bibliotecas do ecossistema de ciência de dados em Python:

- **pandas**: manipulação e análise de dados estruturados  
- **numpy**: operações numéricas e suporte a cálculos  
- **matplotlib** e **seaborn**: visualização de dados  
- **scikit-learn (sklearn)**: preparação de dados e, opcionalmente, construção de modelos preditivos  

Essas ferramentas nos permitirão explorar a base de dados, identificar padrões relevantes e comunicar os resultados de forma clara e visual, com foco na geração de valor para o negócio.

In [ ]:
# Manipulação de dados
import pandas as pd
import numpy as np

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns

# Configuração de estilo
sns.set(style='whitegrid')

# Machine Learning (opcional - etapa 4)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, mean_squared_error

# Configurações adicionais
plt.rcParams['figure.figsize'] = (10, 6)
pd.set_option('display.max_columns', None)

## 2.2 📥 Carregamento da Base de Dados

Nesta etapa, iremos carregar a base de dados contendo informações sobre pedidos, logística, atendimento e satisfação do cliente.

Esses dados serão fundamentais para entender quais fatores operacionais impactam a experiência do cliente e, consequentemente, o Net Promoter Score (NPS).

Após o carregamento, os dados serão armazenados em uma estrutura adequada para análise, permitindo sua manipulação, exploração e transformação ao longo do projeto.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
url = '/content/drive/MyDrive/Fiap | POSTECH/Challenge 01/desafio_nps_fase_1.csv'
df = pd.read_csv(url)

In [ ]:
df.head()

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

**Dimensão da base**

In [ ]:
df.shape
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

Linhas: 2500
Colunas: 19

**Verificar o nome de cada coluna, a quantidade de dados não nulos existente na coluna em questão e o tipo de dado.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                2500 non-null   int64
 1   customer_age               2500 non-null   int64
 2   customer_region            2500 non-null   object
 3   customer_tenure_months     2500 non-null   int64
 4   order_id                   2500 non-null   int64
 5   order_value                2500 non-null   float64
 6   items_quantity             2500 non-null   int64
 7   discount_value             2500 non-null   float64
 8   payment_installments       2500 non-null   int64
 9   delivery_time_days         2500 non-null   int64
 10  delivery_delay_days        2500 non-null   int64
 11  freight_value              2500 non-null   float64
 12  delivery_attempts          2500 non-null   int64
 13  customer_service_contacts  2500 non-null   int64
 14  resolution_time_days       2500 non-null   int64
 15  nps_score                  2500 non-null   float64
 16  repeat_purchase_30d        2500 non-null   int64
 17  complaints_count           2500 non-null   int64
 18  csat_internal_score        2500 non-null   float64
dtypes: float64(5), int64(13), object(1)
memory usage: 371.2+ KB

**Verifcação de valores nulos (visualmente mais claro e informativo)**

In [ ]:
df.isnull().sum()

customer_id                  0
customer_age                 0
customer_region              0
customer_tenure_months       0
order_id                     0
order_value                  0
items_quantity               0
discount_value               0
payment_installments         0
delivery_time_days           0
delivery_delay_days          0
freight_value                0
delivery_attempts            0
customer_service_contacts    0
resolution_time_days         0
nps_score                    0
repeat_purchase_30d          0
complaints_count             0
csat_internal_score          0
dtype: int64

### 📊 **Estrutura da Base de Dados**

A base de dados possui **2.500 registros** e **19 variáveis**, abrangendo diferentes dimensões da jornada do cliente, incluindo perfil, pedidos, logística, atendimento e satisfação.

Do ponto de vista da qualidade dos dados, observa-se que:

- **Não há valores nulos** em nenhuma das variáveis, o que indica uma base completa e consistente para análise;
- As variáveis estão distribuídas da seguinte forma:
  - **13 variáveis numéricas inteiras (int64)**: relacionadas principalmente a contagens e indicadores discretos (ex: quantidade de itens, contatos com atendimento, atrasos);
  - **5 variáveis numéricas contínuas (float64)**: associadas a valores monetários e métricas de avaliação (ex: valor do pedido, frete, NPS);
  - **1 variável categórica (object)**: `customer_region`, representando a localização geográfica do cliente.

---

### 🧩 Interpretação das Variáveis

A base permite analisar a experiência do cliente de forma integrada, a partir de quatro grandes dimensões:

- **Perfil do cliente**:
  - `customer_id`, `customer_age`, `customer_region`, `customer_tenure_months`

- **Dados do pedido**:
  - `order_id`, `order_value`, `items_quantity`, `discount_value`, `payment_installments`

- **Logística**:
  - `delivery_time_days`, `delivery_delay_days`, `freight_value`, `delivery_attempts`

- **Atendimento ao cliente**:
  - `customer_service_contacts`, `resolution_time_days`, `complaints_count`

- **Indicadores de satisfação**:
  - `nps_score`, `csat_internal_score`, `repeat_purchase_30d`

---

### 🎯 Principais Insights Iniciais

- A base apresenta **alta qualidade estrutural**, sem necessidade imediata de tratamento de valores ausentes;
- Há uma **boa diversidade de variáveis explicativas**, o que favorece análises mais robustas sobre os fatores que impactam o NPS;
- A presença simultânea de **indicadores operacionais (logística e atendimento)** e **indicadores de satisfação (NPS e CSAT)** permite investigar relações diretas entre operação e percepção do cliente;
- A variável `nps_score`, definida como target, está disponível e pronta para análise.

---

### ⚠️ Pontos de atenção

- Algumas variáveis podem exigir transformação ou análise mais aprofundada (ex: `delivery_delay_days`, `complaints_count`);
- A variável `customer_region` poderá demandar tratamento categórico para análises mais avançadas;
- É importante verificar a distribuição do `nps_score` na próxima etapa para entender o comportamento da satisfação dos clientes.

## 📈 Estatística Descritiva

In [14]:
df.describe()

,customer_id,customer_age,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
count,2500.00000,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,1250.50000,43.396000,61.322400,51250.50000,434.259740,3.470800,29.745620,6.004000,8.022000,2.187200,38.217016,2.005600,1.519600,5.485600,4.378600,0.087200,4.150400,2.941600
std,721.83216,14.888487,34.478729,721.83216,289.772497,1.687331,29.225603,3.159743,3.770411,1.454442,12.076074,0.815497,1.231512,3.458002,2.510229,0.282184,1.784223,2.378957
min,1.00000,18.000000,1.000000,50001.00000,7.760000,1.000000,0.020000,1.000000,2.000000,0.000000,2.620000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,625.75000,31.000000,31.000000,50625.75000,220.245000,2.000000,8.885000,3.000000,5.000000,1.000000,29.927500,1.000000,1.000000,2.000000,2.600000,0.000000,3.000000,0.700000
50%,1250.50000,43.000000,62.000000,51250.50000,375.515000,3.000000,20.935000,6.000000,8.000000,2.000000,38.500000,2.000000,1.000000,6.000000,4.400000,0.000000,4.000000,2.800000
75%,1875.25000,56.000000,91.000000,51875.25000,577.290000,5.000000,40.832500,9.000000,11.000000,3.000000,46.270000,3.000000,2.000000,8.000000,6.100000,0.000000,5.000000,4.800000
max,2500.00000,69.000000,119.000000,52500.00000,1983.810000,6.000000,230.330000,11.000000,14.000000,8.000000,76.130000,3.000000,7.000000,11.000000,10.000000,1.000000,11.000000,10.000000

In [15]:
df.describe(include='object')

       customer_region
count             2500
unique               5
top                Sul
freq               521

# **III. 📊 Análise Exploratória de Dados (EDA) com Foco em Negócio**

---

##

In [ ]:
df.head()

Ou seja, temos aqui dados categóricos (qualitativos) e numéricos (quantitativos).

### Tipos de Variáveis:

![texto do link](https://github.com/afonsosr2/estatistica-r-frequencias-medidas/blob/main/imagens/outros/tipos_variaveis.png?raw=true)

- **Qualitativas (Categóricas):** São variáveis que representam características ou categorias. Geralmente, são usadas para classificar ou categorizar dados. Por exemplo: sexo biólogico e região
  - **Nominais:** quando não possuem uma ordem natural. (Ex.: tipo de produto).  
  - **Ordinais:** Possuem uma ordem ou hierarquia. (Ex.: Níveis de escolaridade).

- **Quantitativas (Numéricas):** São variáveis que representam números e podem ser mensuradas. Estas variáveis têm significado matemático e podem ser usadas para cálculos. Por exemplo: idade e total de compra
  - **Discretas:** Valores inteiros e contáveis (Ex.: quantidade de produtos).  
  - **Contínuas:** Qualquer valor em um intervalo (Ex.: Altura de pessoas).

Podemos então realizar uma análise simples aqui, investigando uma **variável qualitativa nominal** como, por exemplo, a quantidade de vendas por categoria:

In [ ]:
df['categoria_produto']

In [ ]:
df['categoria_produto'].unique()

In [ ]:
produtos = df['categoria_produto'].value_counts().reset_index()
produtos

In [ ]:
import matplotlib.pyplot as plt
plt.barh(produtos['categoria_produto'], produtos['count'])
plt.show()

Olha só! Apenas analisando uma única coluna já podemos extrair uma informação bem relevante sobre os registros de venda por categoria.

Vamos na sequência analisar e aprender como utilizar uma **variável qualitativa ordinal** deixando-a preparada em nossa base.

## **1.3 Manipulando dados qualitativos ordinais**

---

A gente já observou anteriormente os diferentes tipos de variáveis e começamos a entender como analisar os dados categóricos de uma base.

Uma variável bem interessante em nossa base é a `avaliacao` do produto. Mesmo com dados numéricos, pode ser interpretada como uma variável qualitativa, pois as notas representam uma ordem relacionada a satisfação do cliente. Partindo do Péssimo (nota 1) ao Ótimo (nota 5).

In [ ]:
# Converter para inteiros Python normais
avaliacoes = sorted(df['avaliacao'].unique())
avaliacoes = [int(x) for x in avaliacoes]
print(avaliacoes)
# Resultado: [1, 2, 3, 4, 5]

In [ ]:
df.info()

## Convertendo para int

In [ ]:
df['avaliacao_indicador'] = pd.Categorical(
    df['avaliacao'],
    categories = [1, 2, 3, 4, 5],
    ordered=True
)

In [ ]:
avaliacao_labels = {1: 'Péssimo', 2: 'Ruim', 3: 'Regular', 4: 'Bom', 5: 'Ótimo'}
df['avaliacao_indicador'] = df['avaliacao_indicador'].map(avaliacao_labels)

In [ ]:
df.head()

In [ ]:
df_unico = df[['avaliacao', 'avaliacao_indicador']].drop_duplicates()
df_unico

In [ ]:
df['quantidade'].unique()

Passando por alguns exemplos de variáveis qualitativas em nosso dado. Mas que tal analisarmos também os diferentes dados numéricos?

## **1.4 Diferenciando dados discretos de contínuos**

---

Temos alguns dados numéricos em nossa base de dados. Mas cada variável  tem a sua forma de ser analisada. Algumas delas até com possibilidades de serem encaixadas em 2 ou mais subdivisões.

In [ ]:
df['quantidade'].unique()

In [ ]:
print(f"Vendemos de {min(df['quantidade'])} até {max(df['quantidade'])} unidades de produto por registro")

In [ ]:
df['total_compra'].unique()

In [ ]:
print(f"Tivemos vendas a partir de R${min(df['total_compra']):,.2f} até R${max(df['total_compra']):,.2f}")

In [ ]:
df.sort_values(by='total_compra', ascending=True)

Agora que já entendemos a importância de como trabalhar e analisar diferentes tipos de dados, estamos prontos(as) para responder às perguntas levantadas pelas lideranças da empresa trazendo informações relevantes para o que desejam.

# **2. Identificando o perfil do público**

---

Agora, vamos partir para as análises acerca do perfil do público, como requisitado pelo time de marketing e vendas da empresa varejista que estamos estudando.

Para isso, vamos utilizar uma ferramenta estatística muito importante, que organiza e resume dados em grupos ou classes: a distribuição de frequência. Com ela iremos analisar de maneira mais direta e eficiente as informações dos clientes com os dados qualitativos que possuímos.

Mas, antes disso, vamos interpretar as perguntas que devemos responder e como este tipo de distribuição poderá nos ajudar.

## **2.1 Distribuindo frequências de dados qualitativos - 1 variável**

---

### <font color="#E23155" face="Verdana">Demanda 1: Acompanhamento das avaliações dos clientes</font>

A empresa quer acompanhar as **avaliações dos clientes** sobre seus produtos a fim de priorizar ações, como melhorar produtos com maior proporção de feedbacks negativos, investigar causas e explorar pontos fortes apontados pelos clientes satisfeitos. Essas avaliações variam entre:

1. **Péssimo**
2. **Ruim**
3. **Regular**
4. **Bom**
5. **Ótimo**

Como a **equipe de marketing e vendas** poderá investigar a percepção geral dos clientes sobre os produtos e identificar possíveis comportamentos para ajustar suas estratégias de comunicação e melhoria de produtos?

### <font color="#E23155" face="Verdana">Solução:</font>

### **Distribuição de frequência**

A **distribuição de frequência** é uma tabela que contêm os dados de acordo com a sua **frequência** ($f_i$ = quantidade de vezes que uma determinada variável ocorre). Ela é utilizada tanto para dados **qualitativos** quanto **quantitativos**.

Cada entrada na tabela contém a contagem de ocorrências de valores dentro de um grupo ou intervalo específico, resumindo a distribuição destes valores. Por exemplo, classifica a quantidade de pessoas pelo sexo biológico, a quantidade de itens de um produto vendido, a faixa de renda de pessoas, etc.

#### **Frequência absoluta ($f_i$)**

É o número de vezes em que uma dada observação aparece numa variável. Para cada valor possível, você tem uma dada frequência, cuja soma seria igual a frequência total absoluta, ou melhor, o número total de registros.

# $$F = \sum_{i=1}^{n}f_i = f_1 + f_2 + ... + f_n$$

&nbsp;

#### **Como construir:**

1.  Ordenar os valores das variáveis em ordem crescente ou decrescente;

2.  Determinar a frequência de cada valor;

3.  Agrupar os dados em classes ou intervalos

As avaliações são armazenadas em uma variável chamada `avaliacao_indicador` dentro do banco de dados da empresa.

In [ ]:
df.head()

In [ ]:
freq_avaliacoes = (df.groupby('avaliacao_indicador', observed = False)
                   .size()
                   .reset_index(name='freq_absoluta')
                   .sort_values(by='avaliacao_indicador', ascending = False))
freq_avaliacoes

#### **Frequência relativa ($f_{ri}$)**

Ela é dada pela razão entre a frequência absoluta de cada classe e a frequência total ou soma das frequências absolutas:

# $$f_{ri} = \frac{f_i}{F}$$

Para valores percentuais, basta multiplicar cada frequência relativa por 100.

In [ ]:
freq_avaliacoes['freq_relativa'] = round((freq_avaliacoes['freq_absoluta'] / freq_avaliacoes['freq_absoluta'].sum()) * 100, 2)
freq_avaliacoes

In [ ]:
freq_avaliacoes.columns = ['Avaliação', 'Quantidade', 'Porcentagem (%)']
freq_avaliacoes

In [ ]:
import seaborn as sns
sns.set_theme(style="whitegrid")

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(data=freq_avaliacoes, x='Avaliação', y='Quantidade')

# Adicionando título e rótulos aos eixos
plt.title("Distribuição de Frequências das Avaliações")
plt.xlabel("Avaliação")
plt.ylabel("Frequência")


# Adicionando os rótulos com valores de frequência e porcentagem
for index, row in freq_avaliacoes.iterrows():
    plt.text(index, row['Quantidade'] + 0.1, f"{row['Quantidade']} ({row['Porcentagem (%)']:.1f}%)",
             ha='center', va='bottom', fontsize=12)


plt.show()

Conseguimos perceber que de modo geral possuímos mais avaliações positivas ("Ótimo" e "Bom") que negativas ("Péssimo" e "Ruim"), porém o número de avaliações "Péssimo" está acima das avaliações neutras.

Reportar esse comportamento pode ser importante, pois a equipe de marketing poderá investigar com mais detalhes o que levou a esse nível de avaliação negativa.

## **2.2 Distribuindo frequências de dados qualitativos - 2 variáveis**

---

### <font color="#E23155" face="Verdana">Demanda 2: Avaliações dos clientes por região</font>

A equipe de marketing e vendas da empresa trouxe uma nova demanda para a análise das avaliações. Além de entender o comportamento geral das avaliações (avaliacao_indicador), agora desejam saber também como essas avaliações variam de acordo com a região do país.

Com isso, gostariam de identificar como as percepções dos clientes variam regionalmente, respondendo questões como:

* Qual região tem mais avaliações positivas?
* Alguma região concentra a maior parte das avaliações negativas?
* Existe alguma diferença relevante que indique a necessidade de ações específicas para uma região?

### <font color="#E23155" face="Verdana">Solução:</font>

### **Tabela de contingência (distribuição de frequência bivariada)**

A **tabela de contingência**, também conhecida como tabela cruzada ou tabela bidirecional, tem como objetivo representar de forma resumida a relação entre diferentes variáveis categóricas. Ela é uma espécie de **distribuição de frequência entre 2 variáveis** que analisa a relação entre as variáveis qualitativas, sejam elas dependentes ou independentes.

Geralmente, ela é construída com base em dados qualitativos, os quais são divididos em grupos mutuamente exclusivos. Por exemplo: quantidade de pessoas por sexo biológico e grau de instrução.

Uma das principais utilizações de uma tabela de contingência é analisar a relação entre dados que não são facilmente identificáveis.

In [ ]:
tab_avaliacoes_regiao = pd.crosstab(df['avaliacao_indicador'], df['regiao_cliente'])

In [ ]:
tab_avaliacoes_regiao

#### **Quais as vantagens de uma tabela de contigência**

1. **Visualização das informações:** Organiza dados categóricos num formato compacto e legível, que podem ser transformadas em gráficos;

2. **Análises rápidas:** correlaciona variáveis de forma rápida e visual auxiliando na tomada de decisões informadas e com agilidade;

3. **Testes estatísticos:** Serve como base para realizar testes estatísticos a fim de avaliar a independência entre variáveis categóricas.

In [ ]:
tab_avaliacoes_regiao_relativa = pd.crosstab(df['avaliacao_indicador'], df['regiao_cliente'], normalize = 'columns') * 100

tab_avaliacoes_regiao_relativa = round(tab_avaliacoes_regiao_relativa, 1)

tab_avaliacoes_regiao_relativa

#### ***Qual região tem mais avaliações positivas?***

Considerando "Ótimo" e "Bom" as Regiões Centro-Oeste e Nordeste dividem o ranking de avaliações mais positivas com mais de 55% de satisfação com as compras

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa[tab_avaliacoes_regiao_relativa.index.isin(['Ótimo', 'Bom'])]
resultado = tab_avaliacoes_filtradas.sum()
resultado

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa.loc[['Ótimo', 'Bom']]
tab_avaliacoes_filtradas

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa.loc[['Ótimo', 'Bom']]
resultado = tab_avaliacoes_filtradas.sum()
resultado

#### ***Alguma região concentra a maior parte das avaliações negativas?***

Analisando a tabela de valores absolutos conseguimos notar que a Região Sul tem a maior porcentagem de avaliações negativas (34.3%), sendo a única com quase 20% das notas no nível de satisfação "Péssimo".

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa[tab_avaliacoes_regiao_relativa.index.isin(['Ruim', 'Péssimo'])]
resultado = tab_avaliacoes_filtradas.sum()
resultado

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa.loc[['Ruim', 'Péssimo']]
tab_avaliacoes_filtradas

In [ ]:
tab_avaliacoes_filtradas = tab_avaliacoes_regiao_relativa.loc[['Ruim', 'Péssimo']]
resultado = tab_avaliacoes_filtradas.sum()
resultado

#### ***Existe alguma diferença relevante que indique a necessidade de ações específicas para uma região?***

Sim! Como vimos anteriormente é necessário investigar a baixa avaliação na Região Sul comparada às outras regiões. Outro ponto de atenção está também nas Regiões Sudeste e Norte que concentram cada uma mais de 20% de notas "Regular".

Seriam pontos interessantes de reportar as partes interessadas!

## **2.3 Cruzando os dados dos clientes**

---

### <font color="#E23155" face="Verdana">Demanda 3: Perfil dos clientes</font>

A equipe de marketing e vendas da empresa trouxe mais uma demanda, desta vez, visando traçar o **perfil dos clientes** para melhorar suas campanhas publicitárias. Ela quer entender como o **ticket médio** varia entre o **sexo biológico** e a **região** onde a clientela reside. Com base nessa análise, será possível identificar oportunidades para segmentação de mercado e personalização de campanhas.

Não existe ainda uma análise cruzada dessas informações, portanto, a equipe precisa de uma tabela ou visual que resuma o **ticket médio por sexo e região** para extrair insights sobre o comportamento de consumo.

### <font color="#E23155" face="Verdana">Solução:</font>

A gente já aprendeu a criar uma distribuição de frequência cruzando duas variáveis diferentes. Para este problema precisamos adicionar a estatística descritiva de uma variável quantitativa, no caso a média, dentro dessa nova tabela.

In [ ]:
ticket_medio = round(pd.crosstab(df['sexo_biologico'], df['regiao_cliente'], values=df['total_compra'], aggfunc='mean'), 2)
ticket_medio

In [ ]:
compra_media_regiao = (
    df.groupby('regiao_cliente')['total_compra']
    .mean()
    .round(2)
    .reset_index()
)

compra_media_regiao

In [ ]:
compra_media_regiao.columns = ['Região', 'Ticket Médio']
compra_media_regiao

Temos o total de cada compra dentro do nosso dataset. Precisamos então calcular o ticket médio das pessoas por sexo e região para encontrar, por exemplo, a média de compras de uma pessoa do sexo masculino da região Sudeste ou uma pessoa do sexo feminino da região Norte. Bem interessante, não é?

Observando a matriz, percebemos que as pessoas de sexo biológico masculino possuem um ticket médio acima do feminino nas regiões Centro-Oeste e Nordeste, com uma diferença próxima de **R\$150,00**. Em contrapartida, as pessoas de sexo biológico feminino gastam mais do que o masculino nas regiões Sul e Sudeste, com uma diferença por volta de **R\$300,00** reais.

A análise de ticket médio aqui nos ajudou a entender o comportamento de consumo de diferentes segmentos de clientes.

# **3. Analisando a tendência dos dados**

---

## **3.1 Calculando a média de uma variável**

---

### <font color="#E23155" face="Verdana">Demanda 4: Tempo de entrega por tipo de produto</font>

A equipe de marketing e vendas está buscando formas de melhorar a experiência do cliente, e percebeu que o **tempo de entrega** é um fator crítico para aumentar a satisfação.

Por exemplo, produtos de categorias diferentes, como eletrônicos e roupas, podem ter tempos de entrega distintos devido a fatores como peso, localização dos fornecedores e demanda.

Por isso, precisamos calcular o **tempo médio de entrega para cada categoria de produto** com base nos dados históricos, visando fornecer estimativas mais precisas no site e permitir ajustes na logística.

### **Medidas de Tendência Central**

As **medidas de tendência central** são ferramentas estatísticas que ajudam a descrever as características dos dados resumindo-os em um único valor. Essas medidas (média, mediana e moda) são utilizadas em diversas análises e técnicas visando extrair informações dos dados.

### **Média aritmética ($\mu$)**

A **média aritmética**  é uma das mais conhecidas medidas de resumo. Ela é a soma de todos os valores divididos pelo número de observações. Representa um ponto central dos dados, ou seja, um ponto de equilíbrio.


# $$\mu = \frac 1n\sum_{i=1}^{n}X_i = \frac{X_1 + X_2 + ... + X_n}{n}$$

Onde:

$n$ = número de observações (registros)

$X_i$ = valor da i-ésima observação (registro)

### <font color="#E23155" face="Verdana">Solução:</font>

In [ ]:
media_entrega_geral = round(df.tempo_entrega.mean(), 2)
media_entrega_geral

In [ ]:
media_entrega_geral = round(float(df['tempo_entrega'].mean()), 2)
print(media_entrega_geral)
# Resultado: 10.04

In [ ]:
media_entrega_geral = round(df['tempo_entrega'].mean().item(), 2)
print(media_entrega_geral)
# Resultado: 10.04

#### ***A média é sempre a melhor forma de resumir os dados***

A resposta é **não**! Por ser um ponto de equilíbrio, em algumas análises ela pode não ser a forma mais correta de indicar a tendência central.

Isto porque ela é muito influenciada pelos extremos da distribuição. Entretanto, com outras informações aliadas à média podemos tirar boas conclusões e investigar se precisamos ou não de algum tratamento e/ou transformação do dado.

In [ ]:
media_entrega_cat = df.groupby('categoria_produto')['tempo_entrega'].mean().reset_index().round(1)
media_entrega_cat

In [ ]:
media_entrega_cat.columns = ['Categoria', 'Tempo Médio de Entrega']
media_entrega_cat = media_entrega_cat.sort_values(by='Tempo Médio de Entrega', ascending=False)
media_entrega_cat

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(data=media_entrega_cat, x='Tempo Médio de Entrega', y='Categoria')
plt.axvline(media_entrega_geral, color='red', linestyle='-')

plt.xlabel('Tempo Médio de Entrega')
plt.ylabel('Categoria')

plt.show

Como a empresa não possuia informações precisas sobre como os tempos de entrega variam entre as categorias de produtos, isso dificultava a definição de estimativas para os clientes, gerando frustrações quando o tempo real de entrega não corresponde ao esperado.

Aqui conseguimos apontar os gargalos e quais as categorias que precisam de atenção, seja pela dificuldade de transporte ou outros problemas.

## **3.2 Aplicando a mediana na investigação dos dados**

---

### <font color="#E23155" face="Verdana">Demanda 5: Vendas de eletrônicos na região Nordeste</font>

Para nossa nova demanda, a divisão da equipe de marketing e vendas que cuida das vendas no Nordeste está buscando investigar o comportamento dos consumidores nessa área, devido ao crescimento significativo nas vendas de **Eletrônicos**. A equipe deseja entender melhor a distribuição dos valores de vendas para ajustar sua estratégia de preços e campanhas.

Embora a média das vendas de eletrônicos forneça uma visão geral, ela pode ser influenciada por valores extremos, como compras muito altas ou muito baixas.

Para capturar um retrato mais representativo do comportamento típico dos consumidores qual medida podemos utilizar?

### **Mediana ($M_d$)**

A **mediana** representa o valor central de um conjunto de dados, passando o número que divide um conjunto de dados exatamente ao meio. Para obtermos a mediana de uma conjunto de dados devemos proceder da seguinte maneira:

1. Ordenar o conjunto de dados;
2. Identificar o número de observações (registros) do conjunto de dados ($n$);
3. Identificar o elemento mediano:

$$ Elemento_{Md} = \left\{\begin{matrix}
\frac{n+1}2 & ,se \ n \ for \ ímpar \\
 &  \\
\frac{n}2 & ,se \ n \ for \ par \\
\end{matrix}\right.$$

&nbsp;

4. Obter a mediana:

$$ M_d = \left\{\begin{matrix}
X_{Elemento_{Md}} & ,se \ n \ for \ ímpar \\
 &  \\
\frac{X_{Elemento_{Md}} + X_{Elemento_{Md}+1}}2 & ,se \ n \ for \ par \\
\end{matrix}\right.$$

&nbsp;

### <font color="#E23155" face="Verdana">Solução:</font>

##### **Usando a fórmula**

In [ ]:
dados_nordeste = df[(df['regiao_cliente'] == 'Nordeste') &
                  (df['categoria_produto'] == 'Eletrônicos')]
dados_nordeste = dados_nordeste.sort_values(by='total_compra', ascending=False).reset_index(drop=True)
dados_nordeste.head()

In [ ]:
n = len(dados_nordeste)
n

In [ ]:
elemento_md = int(n / 2)
elemento_md

In [ ]:
# Como o elemento mediano é par, o valor mediano será aquele na posição do elemento mediano (4436 - 1) + o elemento mediano mais 1 (4436-1 + 1) dividido por 2. Porque o primeiro elemento do DataFrame é 0.
round((dados_nordeste['total_compra'].iloc[elemento_md - 1] + dados_nordeste['total_compra'].iloc[elemento_md]) / 2, 2)

In [ ]:
# Se você quer as linhas na posição 4435 e 4436 (após o sort)
dados_nordeste.iloc[[4435, 4436]]

##### **Usando a função `median()`**

In [ ]:
mediana = round(dados_nordeste.total_compra.median(), 2)
mediana

In [ ]:
media = dados_nordeste.total_compra.mean()
media

#### ***Por que usar a mediana ao invés da média neste caso?***

Porque a **média** pode ser influenciada por valores extremos, enquanto a **mediana** reflete o ponto central das vendas, oferecendo uma medida de tendência central mais adequada em casos de dados assimétricos.

A mediana indica aqui que metade dos clientes gasta até, aproximadamente, R\$ 2.990,00 em eletrônicos, enquanto a média (R$ 3.970,00) sugere que há vendas bastante altas puxando o valor médio para cima.

---

##### **Visualizando diferença graficamente**

Para visualizar essa discrepância entre os dados, vamos criar um gráfico chamado **histograma**. Ele é uma espécie de gráfico de barras que demonstra uma distribuição de frequências.

No histograma, a base de cada uma das barras representa uma classe e a altura representa a quantidade ou frequência absoluta com que o valor de cada classe ocorre.

In [ ]:
sns.histplot(dados_nordeste.total_compra, bins=30)
plt.axvline(mediana, color='blue', linestyle='--')
plt.axvline(media, color='red', linestyle='--')
plt.show()

Como os dados de vendas de eletrônicos tiveram valores muito altos, o que elevou a média para **uma diferença de quase R$1.000,00** em relação à mediana, a mediana oferece uma métrica mais confiável para entender o comportamento típico do consumidor.

Neste caso, a mediana seria o ideal para reportar ao time de vendas como valor esperado de compra das pessoas clientes da empresa na Região Nordeste para produtos eletrônicos.

Essa informação pode auxiliar em estratégias de vendas como, por exemplo:

1. Criar promoções em produtos na faixa da mediana para atrair mais consumidores "típicos".
2. Destacar os produtos de alto valor nas campanhas de marketing para atingir clientes dispostos a gastar mais.

Como desafio, que tal você analisar também as medianas para os diferentes sexos biológicos?

## **3.3 Identificando os valores mais frequentes**

---

### <font color="#E23155" face="Verdana">Demanda 6: Campanha promocional de livros</font>

A equipe de marketing e vendas da empresa em que estamos prestando consultoria, está planejando uma nova campanha promocional de "Pague X e Leve Y Livros". Para definir a quantidade de livros a ofertar no pacote, eles decidiram basear-se na quantidade de livros mais frequentemente comprada pelos clientes. Isso permite criar uma promoção direcionada ao comportamento mais comum dos consumidores.

Precisamos então identificar qual ou quais quantidades de livro são mais frequentes para a campanha, maximizando a relevância e atratividade da promoção.

### **Moda ($M_o$)**

A **moda** representa o valor mais frequente de um conjunto de dados. Para obtermos a moda, basta observar a frequência com que os valores aparecem no conjunto de dados.

Esta medida é bastante utilizada para dados qualitativos, mas também tem aplicações em dados numéricos como em nosso exemplo.

### <font color="#E23155" face="Verdana">Solução:</font>

In [ ]:
df['regiao_cliente'].value_counts()

Existem $n$ formas de encontrar a moda de uma variável. Em dados qualitativos, podemos contar, por exemplo, as ocorrências e pegar a que mais se repete. Já fizemos isso por meio das distribuições de frequência para uma variável.

In [ ]:
dados_filtrados = df[df['categoria_produto'] == 'Livros']
dados_filtrados.head()

#### ***Quais cuidados devemos ter com a moda?***

Por ser o valor mais frequente em um conjunto de dados, em dados numéricos é possível que haja repetições e, por isso, teremos mais de 1 moda (multimodalidade).

É importante decidir como lidar com esses casos para atingir o comportamento desejado.

A outra forma, utilizando dados quantitativos e/ou qualitativos é por meio também da contagem para cada ocorrência, mas filtrando os máximos ao final, para verificar se a amostra possui uma única moda ou mais.

In [ ]:
moda = dados_filtrados['quantidade'].mode()
moda

Conseguimos observar aqui que temos **2 modas** na quantidade de livros vendidos (**bimodal**) e, portanto, podemos reportar esse resultado ficando a cargo da empresa qual campanha realizar.

Será que vale a pena para menos livros ou para mais livros? Ou seria melhor 2 campanhas como "Pague 2 e Leve 3" e "Pague 4 e leve 6", verificando qual converte mais clientes e gera mais vendas?

## **3.4 Compreendendo a relação entre média, mediana e moda**

---

### <font color="#E23155" face="Verdana">Demanda 7: Investigando as avaliações e sua relação com o tempo de entrega</font>

A equipe de marketing e vendas da empresa recebeu feedbacks de clientes sobre o tempo de entrega. Eles notaram que avaliações "Ótima" (nota 5) podem ter certa  relação com o tempo de entrega.

A hipótese é que clientes mais satisfeitos (nota 5) tendem a ter um tempo de entrega mais curto, mas isso só pode ser confirmado analisando os dados.
Com isso, queremos explorar:
* As distribuições do tempo de entrega e o que as medidas de tendência central podem nos informar.
* Se o comportamento das avaliações nota 5 realmente indica que entregas mais rápidas são mais apreciadas pelos clientes.

### <font color="#E23155" face="Verdana">Solução:</font>

Faremos uma análise em duas etapas:

1. **Distribuição do tempo de entrega:** calcularemos média, mediana e moda e visualizaremos a curva de densidade.
2. **Distribuição para avaliações nota 5:** repetiremos o processo para o caso, comparando os resultados com a distribuição geral.

### Relação entre média, mediana e moda:

Investigar a relação entre as medidas de tendência central pode ser bastante útil para identificar se uma variável é simétrica ou assimétrica, se precisa de algum tipo de transformação ou se é uma forte candidata a ter "outliers".

Abaixo, temos 3 tipos de comportamentos e como as estatísticas se posicionam em cada uma delas:

![texto do link](https://github.com/afonsosr2/estatistica-r-frequencias-medidas/blob/main/imagens/outros/relacao_media_mediana_moda.png?raw=true)

Vamos começar com a distribuição do tempo de entrega. Vou primeiro construir um histograma com uma curva de densidade, semelhante a um dos exemplos de cima para observar o comportamento dos tempos de entrega da empresa.

In [ ]:
sns.histplot(bins=21, data=df, x='tempo_entrega', kde=True, kde_kws={'bw_adjust':2})
plt.show()

In [ ]:
df.tempo_entrega.mode()[0]

In [ ]:
tempo_entrega_resumo = {
    'média' : df['tempo_entrega'].mean(),
    'mediana' : df['tempo_entrega'].median(),
    'moda' : df['tempo_entrega'].mode()[0]
}
tempo_entrega_resumo

A análise inicial revelou que o tempo de entrega segue uma **distribuição normal simétrica**.

Precisamos agora investigar se a distribuição muda para tempos de entrega com vendas com notas de satisfação 5.

Nossa hipótese é que esta distribuição sera apresentada com uma **curva assimétrica à direita**. O que pode sugerir que entregas mais rápidas podem estar relacionadas a maior satisfação do cliente.

In [ ]:
dados_nota_5 = df[df['avaliacao'] == 5]
dados_nota_5.head()

In [ ]:
sns.histplot(bins=21, data=dados_nota_5, x='tempo_entrega', kde=True, kde_kws={'bw_adjust':2})
plt.show()

In [ ]:
resumo = {
    'média' : dados_nota_5['tempo_entrega'].mean(),
    'mediana' : dados_nota_5['tempo_entrega'].median(),
    'moda' : dados_nota_5['tempo_entrega'].mode()[0]
}
resumo

Os dados confirmam que entregas mais rápidas estão associadas a avaliações nota 5, embora algumas poucas entregas mais longas ainda recebam notas altas. Esses insights destacam a importância de **manter prazos curtos de entrega para maximizar a satisfação dos clientes**.

Com essa análise, a equipe de marketing e vendas aliada à logística pode usar os resultados para:

1. Otimizar rotas e processos de entrega para reduzir o tempo de entrega médio.
2. Diferenciar campanhas promocionais com base na promessa de entregas rápidas.

# **4. Investigando os dados dos colaboradores**

---

Agora, vamos partir para análises das remunerações dos colaboradores, a pedido do setor do RH e financeiro da empresa da empresa de e-commerce.

Vamos prosseguir utilizando alguns conceitos da estatística para investigar os dados que trazem informações sobre a remuneração dos colaboradores, passando pelos salários, desempenho atual. Vamos trazer alguns insights analisando criticamente, por exemplo, a equidade salarial entre cargos e gênero e respondendo a perguntas do setor do RH e financeiro da empresa.

## **4.1 Criando o histograma de salários com amplitude fixa**

---

### <font color="#E23155" face="Verdana">Demanda 8: Iniciando as análises da remuneração dos colaboradores

</font>

A equipe de RH e financeiro da empresa de e-commerce que estamos prestando consultoria quer investigar a distribuição dos salários dos colaboradores para identificar possíveis faixas salariais e verificar a concentração de colaboradores em determinados intervalos. Essas informações serão usadas para ajustar benefícios, analisar disparidades salariais e planejar estratégias de retenção de talentos.

Nosso objetivo, é ler a base com os dados e criar uma distribuição de frequências com base em classes de salários utilizando os conceitos da estatística tanto para visualizar os dados em um histograma quanto para identificar as faixas salariais mais representativas.

### <font color="#E23155" face="Verdana">Solução:</font>

Para calcular o número de classes utilizaremos a **Regra de Sturges** para em sequência segmentar os salários em faixas e calcular a frequência absoluta e relativa de cada faixa. Por fim, construiremos um histograma para visualizar os dados.

#### **Definindo o número de classes**

##### **Regra de Sturges**

Calcula o número de classes de uma distribuição com base no tamanho da amostra:

# $$k = 1 + \frac {10}{3}\log_{10}n$$

onde,

$k$ = número de classes

$n$ = número de observações.

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Estatisticas-Python-frequencias-medidas/refs/heads/main/dados/colaboradores.csv'
colaboradores = pd.read_csv(url)
colaboradores

In [ ]:
n = len(colaboradores)
n

In [ ]:
import math

In [ ]:
k = 1 +(10 / 3) * math.log10(n)
k

In [ ]:
k = int(k)
k

In [ ]:
faixas = colaboradores.copy()
faixas

In [ ]:
faixas['faixa_salarial'] = pd.cut(faixas['remuneracao'], bins=k, include_lowest=True)
faixas

#### **Criando a tabela de frequências**

In [ ]:
tabela_frequencias = faixas.groupby('faixa_salarial', observed=False).size().reset_index(name='frequencia')

# Calculando a percentagem
tabela_frequencias['porcentagem'] = round((tabela_frequencias['frequencia'] / len(colaboradores)) * 100, 2)

tabela_frequencias

A tabela de frequências mostra os intervalos de salários (faixas) e a concentração de colaboradores em cada uma.

* Podemos observar que mais da metade dos colaboradores (52,5%) são remunerados dentro da 1ª faixa (de R\$ 1.890,00 até R\$4.080,00).
* Proporção de Colaboradores: A coluna de porcentagem fornece insights sobre a distribuição relativa dos colaboradores, útil para comparações.

#### **Construindo o histograma**

In [ ]:
plt.figure(figsize=(15, 6))
sns.histplot(data=faixas, x='remuneracao', bins=k, kde = True)
plt.show()

In [ ]:
sns.histplot(data = colaboradores, x = 'remuneracao', bins = k, kde = True)
plt.show()

O histograma apresenta a distribuição visual da nossa tabela de frequência. Conseguimos notar um comportamento assimétrico à direita, como esperado para salários em uma empresa.
Notamos que a distribuição de salários está com mais de 95% das remunerações até R\$ 10.000,00.

## **4.2 Avaliando os salários pelas medidas separatrizes**

---

### <font color="#E23155" face="Verdana">Demanda 9: Análise de remuneração dos colaboradores</font>

Agora, a equipe de RH e financeiro da empresa quer entender melhor a distribuição dos salários dos colaboradores dentro de faixas específicas. Há um interesse em identificar faixas salariais e entender se a remuneração das pessoas coordenadoras estão dentro dos 99% maiores salários.

Como calcular e interpretar esses dados para gerar insights úteis ao RH e ao financeiro? Além disso, como comunicar essas análises de forma clara para orientar decisões estratégicas?

### **Quartis, decis e percentis**

São medidas de posição semelhantes à mediana, embora não sejam medidas de tendência central. Como se sabe, a mediana divide a distribuição em duas partes iguais quanto ao número de elementos de cada parte. Para essas 3 medidas temos:

* **Quartis:** Dividem os dados em 4 partes iguais de acordo com o número de registros, sendo bastante importante para identificar faixas.

* **Decis:** Dividem os dados em 10 partes iguais.

* **Percentis:** Dividem os dados em 100 partes iguais, que ajuda em análises mais granulares, como os 5% ou 1% maiores valores.

### <font color="#E23155" face="Verdana">Solução:</font>

Para os salários, utilizaremos os quartis para observar as faixas salariais e o percentil acima de 99% para identificar se as pessoas coordenadoras estão entre os salários mais altos.

#### **Calculando os quartis**

In [ ]:
quartis = {
    'Q1' : colaboradores['remuneracao'].quantile(0.25),
    'Q2' : colaboradores['remuneracao'].quantile(0.50),
    'Q3' : colaboradores['remuneracao'].quantile(0.75),
    'Q4' : colaboradores['remuneracao'].quantile(1)
}
quartis

#### **Visualizando os quartis em um Histograma**

In [ ]:
plt.figure(figsize=(15, 6))
sns.histplot(data=colaboradores, x='remuneracao', binwidth = 500, bins=k)
plt.axvline(quartis['Q1'], color='red', linestyle='--')
plt.axvline(quartis['Q2'], color='blue', linestyle='--')
plt.axvline(quartis['Q3'], color='green', linestyle='--')
plt.axvline(quartis['Q4'], color='black', linestyle='--')
plt.show()

Com os quartis conseguimos dividir as faixas salariais em partes iguais. Aqui conseguimos observar que por conta dos altos salários dos cargos mais gerenciais da empresa, temos uma **distribuição mais assimétrica** da remuneração.

O que é um comportamento esperado para salário: muitos recebem um valor base e poucos com altos salários.

#### **Analisando os salários das pessoas coordenadoras**

Vamos prosseguir nossa investigação verificando se as pessoas coordenadoras (3º em hierarquia na nossa base) estão entre os 1% com maiores salários.

In [ ]:
percentil_99 = colaboradores['remuneracao'].quantile(0.99)
percentil_99

In [ ]:
coordenadores = colaboradores[colaboradores['cargo'] == 'Coordenador(a)'].reset_index(drop=True)
coordenadores
num_coordenadores = len(coordenadores)
num_coordenadores

In [ ]:
coordenadores

In [ ]:
coordenadores_alta_remuneracao = colaboradores[(colaboradores['cargo'] == 'Coordenador(a)') & (colaboradores['remuneracao'] > percentil_99)]
num_coordenadores_alta_remuneracao = len(coordenadores_alta_remuneracao)
num_coordenadores_alta_remuneracao

Com isso, conseguimos comprovar que as pessoas coordenadoras estão entre os 1% que recebem maiores salários dentro da empresa. Podemos repassar essa informação para o RH e financeiro da empresa para averiguar se está dentro das políticas salariais. E, se possível, analisando mais perfis, eles poderão definir políticas de remuneração mais transparentes e alinhadas ao mercado.

## **4.3 Classificando dados pelas medidas separatrizes**

---

### <font color="#E23155" face="Verdana">Demanda 10: Pesquisa de colaboradores mais jovens</font>

Nesta nova demanda, a equipe de RH da empresa quer realizar uma pesquisa em torno das idades dos colaboradores. Isto porque a empresa deseja identificar o grupo mais jovem (**20% mais novos**) para implementar um programa de aceleração profissional com cursos e treinamentos voltados ao desenvolvimento de jovens talentos.

Como calcular e interpretar esses dados para repassar ao RH?

### <font color="#E23155" face="Verdana">Solução - Analisando as idades:</font>

Para as idades, visualizaremos a distribuição, classificaremos as idades percentualmente, e determinaremos o ponto de corte para o grupo de 20% mais jovens, que poderão ser contemplados com o programa de aceleração profissional.

#### **Visualizando a faixa etária desejada**

In [ ]:
plt.figure(figsize=(15, 6))
sns.histplot(data=colaboradores, x = 'idade', bins = 10, cumulative = True, stat = 'proportion', kde = True)
plt.axhline(y = 0.2, color='red', linestyle='--')
plt.show()

#### **Classificando os colaboradores e identificando público**

In [ ]:
idades_classificacao = colaboradores.copy()
idades_classificacao.head()

In [ ]:
# 1. Ordenar os dados pela coluna 'idade'
idades_classificacao = idades_classificacao.sort_values(by='idade')

# 2. Adicionar a coluna 'cumulativo' (posição relativa de cada linha)
idades_classificacao['cumulativo'] = (idades_classificacao.reset_index().index + 1) / len(idades_classificacao)

# 3. Adicionar a coluna 'qualificado' com base no valor de 'cumulativo'
idades_classificacao['qualificado'] = idades_classificacao['cumulativo'] <= 0.20

idades_classificacao

In [ ]:
idades_classificacao = idades_classificacao[idades_classificacao['qualificado'] == True].reset_index(drop=True)
idades_classificacao

In [ ]:
len(idades_classificacao)

Com base na análise, identificamos que há **2.218 pessoas** qualificadas para o programa, representando os **20% mais jovens do total de colaboradores**. Esse grupo pode ser o alvo ideal para o programa de aceleração profissional, já que engloba aqueles que estão no início de suas carreiras.

Agora, podemos reportar ao RH a lista de funcionários dentro da qualificação desejada, o que ajudará no planejamento do programa para jovens talentos, fortalecendo a cultura organizacional e promovendo o desenvolvimento profissional.

## **4.4 Construindo um boxplot para visualização das distribuições**

---

### <font color="#E23155" face="Verdana">Demanda 11: Análise de remuneração dos colaboradores pelo sexo</font>

A equipe de RH e financeiro da empresa requisitou uma nova análise das distribuições salariais. Ela tem interesse em investigar as diferenças salariais entre os sexos biológicos masculino e feminino, buscando informações para reforçar a importância de garantir a equidade salarial.

Os dados salariais não são fáceis de interpretar em tabelas ou gráficos convencionais. É necessário um visual que permita identificar algumas medidas de tendência central , faixas de salário e até possíveis outliers, além de comparar visualmente as distribuições entre diferentes grupos.

Com isso, o RH também pode direcionar ações voltadas à igualdade salarial.

### **Boxplot**

![texto do link](https://github.com/afonsosr2/estatistica-r-frequencias-medidas/blob/main/imagens/outros/boxplot.png?raw=true)

O **boxplot** é uma representação visual que mostra a distribuição de dados quantitativos, facilitando comparações entre variáveis ou categorias.

Os elementos principais de um boxplot são:

* **Caixa:** Representa o intervalo
interquartil (IIQ), que vai do primeiro quartil (Q1 - 25% dos dados) ao terceiro quartil (Q3 - 75% dos dados).

* **Linha mediana:** Onde está posicionado a mediana (Q2), valor que separa 50% dos dados.

* **Whiskers ("bigodes"):** Extensões que mostram a variabilidade fora do intervalo interquartil, geralmente até 1,5 vezes o IIQ a partir dos quartis.

* **Outliers:** Pontos individuais que estão fora do alcance dos *whiskers*, indicados separadamente.

Essa visualização ajuda a identificar a centralidade, dispersão e possíveis outliers em um conjunto de dados.

### <font color="#E23155" face="Verdana">Solução:</font>

Vamos construir e interpretar boxplots para visualizar a distribuição das variáveis. Analisaremos diferenças salariais entre os sexos e discutiremos possíveis ações para promover equidade.

In [ ]:
plt.figure(figsize=(8, 6))
sns.boxplot(x=colaboradores['remuneracao'], color='steelblue')

plt.title('Boxplot de Salários')
plt.xlabel('Salário (R$)')

plt.ylim(-1, 1)

plt.show()

Para sabermos os valores de cada elemento do boxplot, podemos utilizar as funções quando estudamos os quartis das remunerações ou chamar a função `describe()` que resume nossos dados com as principais estatísticas descritivas.

In [ ]:
colaboradores['remuneracao'].describe()

Agora, vamos partir para o foco da nossa análise que é a comparação entre os sexos biológicos:

In [ ]:
plt.figure(figsize=(8, 6))
ax = sns.boxplot(x='remuneracao', y='sexo_biologico', data=colaboradores, hue='sexo_biologico')

plt.title('Boxplot de Salários por Sexo Biológico')
plt.xlabel('Salário (R$)')
plt.ylabel('Sexo Biológico')

plt.show()

Aplicando a análise visual, conseguimos notar que aparentemente as pessoas do sexo masculino possuem uma distribuição salarial maior que a do sexo feminino, mas com os candidatos à outliers que temos ainda não fica tão clara essa diferença.

> **Obs:** Outliers indicam indivíduos com salários significativamente maiores ou menores.

Como estudamos anteriormente, mais de 95% das remunerações chegam até R$ 10.000,00. Podemos usar esse fator para filtrar os dados e observar com mais facilidade essa diferença salarial.

In [ ]:
colaboradores_filtrados = colaboradores[colaboradores['remuneracao'] <= 10000]
colaboradores_filtrados.head()

In [ ]:
plt.figure(figsize=(8, 6))
ax = sns.boxplot(x='remuneracao', y='sexo_biologico', data=colaboradores_filtrados, hue='sexo_biologico')

plt.title('Boxplot de Salários por Sexo Biológico')
plt.xlabel('Salário (R$)')
plt.ylabel('Sexo Biológico')

plt.show()

Notamos aqui que **a mediana dos salários para pessoas do sexo feminino é menor** que a das pessoas com sexo masculino, sendo o primeiro abaixo **R$ 4.000,00** e o segundo acima desse valor.

Para reforçar a análise, vamos calcular as estatísticas descritivas para cada grupo.

In [ ]:
estat_remuneracao = colaboradores.groupby('sexo_biologico')['remuneracao'].agg(
    Q1 = lambda x: x.quantile(0.25),
    mediana = 'median',
    media = 'mean',
    Q3 = lambda x: x.quantile(0.75),
    IIQ = lambda x: x.quantile(0.75) - x.quantile(0.25)
).reset_index()
estat_remuneracao

Podemos reportar os resultados para o RH da empresa que deve investigar as causas, especialmente ao considerar cargos similares. Com isso, será possível que a equipe realize ações que busquem revisar políticas salariais para garantir igualdade e realizar análises adicionais considerando fatores como cargo, experiência e desempenho.

# **5. Analisando as variações dos dados**

---

## **5.1 Calculando o desvio médio absoluto**

---

### <font color="#E23155" face="Verdana">Demanda 12: Analisando diferenças salariais - Parte 1</font>

A equipe de RH e financeiro da empresa de e-commerce recebeu alguns feedbacks sobre uma possível falta de padrão entre os salários dos cargos de **Inteligência comercial** e **Consultor(a) de vendas**.

Com que aprendemos até o momento, apenas as medidas de tendência central (média e mediana) não são suficientes para avaliar a uniformidade dos salários. É necessário um indicador de dispersão que mostre como os salários se distribuem em relação à média, revelando inconsistências.

O objetivo é investigar as faixas salariais desses cargos.

#### **Medidas de dispersão**
As **medidas de dispersão** são utilizadas para indicar o grau da variação dos valores de uma variável quantitativa em relação à sua média.

Embora as medidas de tendência central e de posição forneçam uma sumarização bastante importante dos dados, elas podem não ser suficientes para caracterizar conjuntos distintos, especialmente quando as observações de determinada distribuição apresentarem dados muito dispersos.

#### **Desvio médio absoluto (MAD)**
O **Desvio Médio Absoluto (MAD)** é uma medida para avaliar a dispersão dos dados que representa a média das diferenças absolutas entre cada valor e a média dos dados.

# $$MAD = \frac 1n\sum_{i=1}^{n}|X_i-\bar{X}|$$

Onde:

$n$ = número de observações

$X_i$ = valores da i-ésima variável

$\bar{X}$ = a média da distribuição

### <font color="#E23155" face="Verdana">Solução:</font>

#### **Ler as estatísticas descritivas das remunerações**

Vamos começar lendo os valores de tendência central dos salários dos cargos de Inteligência comercial e Consultor(a) de vendas

In [ ]:
comercial = colaboradores[colaboradores['cargo'].isin(['Inteligência comercial', 'Consultor(a) de vendas'])]
comercial

In [ ]:
comercial.groupby('cargo')['remuneracao'].describe()[['mean', '50%']]

Conseguimos notar que as médias e medianas estão bem próximas, então parece tudo ok, certo?

**Não!** As medidas de tendência central servem para trazer um valor que generaliza nosso dado, mas que não representa a dispersão entre eles. Neste caso precisamos utilizar as medidas de dispersão para ter uma noção.

#### **Observando as variações das remunerações**

In [ ]:
import numpy as np
np.random.seed(42)

amostra = comercial.sample(10)
amostra

In [ ]:
plt.stem(amostra['remuneracao'], bottom = amostra['remuneracao'].mean())
plt.axhline(y = amostra['remuneracao'].mean(), color = 'red', linestyle = '--')
plt.show()

In [ ]:
estat_colab = comercial.groupby('cargo')['remuneracao'].agg(
    media = 'mean',
    mediana = 'median',
    mad = lambda x: np.mean(np.abs(x - x.mean())),
).reset_index()
estat_colab

Como dito anteriormente a média e mediana estão próximas entre os dois cargos. E o desvio médio absoluto é ligeiramente maior para as pessoas consultoras,  indicando maior dispersão se comparada com as pessoas da Inteligência comercial. Podemos visualizar graficamente essa variação entre elas.

#### **Visualizando graficamente**

In [ ]:
plt.figure(figsize=(8, 6))
sns.boxplot(x='remuneracao', y='cargo', data=comercial, hue='cargo')

plt.title('Distribuição de Salários por Cargo')
plt.xlabel('Salário (R$)')
plt.ylabel('Cargo')

plt.show()

Conseguimos observar os comportamentos dos salários entre os profissionais de inteligência comercial e consultoria de vendas e percebemos que ambos têm média e mediana salariais muito próximas, com uma variação ligeiramente superior do cargo de inteligência comercial, que foi comprovado tanto pelo MAD quanto observando o intervalo interquartil (IIQ).

A equipe de RH pode usar esses dados para:

* Investigar os critérios de definição salarial para ambos, visto que o esperado era ter o mesmo nível salarial.
* Estabelecer políticas salariais mais padronizadas para cargos equivalentes ou ser mais transparente na definição salarial dentro da empresa.

## **5.2 Calculando a variância e desvio padrão**

---

### <font color="#E23155" face="Verdana">Demanda 12: Analisando diferenças salariais - Parte 2</font>

A equipe de RH e financeiro da empresa de e-commerce também recebeu alguns feedbacks sobre uma possível falta de padrão entre os salários de dois cargos operacionais, Estoquista e Repositor(a), que representam o maior volume de funcionários da empresa.

O objetivo é investigar também as faixas salariais desses cargos, determinar qual deles apresenta maior inconsistência e identificar padrões que possam sugerir desigualdades ou problemas de política salarial.

#### **Variância ($\sigma^2$ ou $S^2$)**
A **variância** é uma medida de dispersão que mostra o quão distante cada valor de uma variável quantitativa está da média da sua distribuição.

Ela é construída a partir das diferenças entre cada observação e a média dos dados, ou seja, o desvio em torno da média. No cálculo da variância, os desvios em torno da média são elevados ao quadrado.

##### **Variância populacional**

# $$\sigma^2 = \frac 1n\sum_{i=1}^{n}(X_i-\mu)^2$$

##### **Variância amostral**

# $$S^2 = \frac 1{n-1}\sum_{i=1}^{n}(X_i-\bar{X})^2$$

Onde:

$n$ = número de observações

$X_i$ = valores da i-ésima variável

$\mu$ e $\bar{X}$ = média da população e amostra da distribuição, respectivamente

### <font color="#E23155" face="Verdana">Solução:</font>

#### **Ler as estatísticas descritivas das remunerações**

Vamos começar lendo os valores de tendência central dos salários dos cargos de Estoquista e Repositor(a)

In [ ]:
operacional = colaboradores[colaboradores['cargo'].isin(['Estoquista', 'Repositor(a)'])]
operacional

In [ ]:
operacional.groupby('cargo')['remuneracao'].describe()[['mean', '50%']]

Conseguimos notar que novamente as médias e medianas estão bem próximas. Precisamos utilizar as medidas de dispersão para ter uma noção se realmente temos uma diferença relevantes entre os salários dos dois cargos.

In [ ]:
estatisticas_operacional = operacional.groupby('cargo')['remuneracao'].agg(
    media = 'mean',
    mediana = 'median',
    variancia = 'var',
).reset_index()
estatisticas_operacional

Números bem altos não é mesmo? O que isso significa?

Como variância fornece os valores das medidas ao quadrado, representar o nosso resultado dessa forma dificultaria a comparação da dispersão com as variáveis que a definem.

Um modo de eliminar essa dificuldade é utilizando o **desvio padrão**

#### **Desvio padrão ($\sigma$ ou $S$)**

O desvio padrão é uma medida de dispersão que indica o grau de dispersão de um conjunto de dados. É expresso pela raiz quadrada da variância populacional ou amostral.

Além de expressar a variabilidade da população, o desvio padrão pode ser utilizado para medir a confiança (nível de acerto esperado de uma estimativa) e geralmente permite sintetizar os resultados de amostras.


##### **Desvio padão populacional**

# $$\sigma = \sqrt{\frac 1n\sum_{i=1}^{n}(X_i-\mu)^2} \Longrightarrow \sigma = \sqrt{\sigma^2}$$

##### **Desvio padrão amostral**

# $$S = \sqrt{\frac 1{n-1}\sum_{i=1}^{n}(X_i-\bar{X})^2} \Longrightarrow S = \sqrt{S^2}$$

Onde:

$n$ = número de observações

$X_i$ = valores da i-ésima variável

$\mu$ e $\bar{X}$ = média da população e amostra da distribuição, respectivamente

In [ ]:
estatisticas_operacional = operacional.groupby('cargo')['remuneracao'].agg(
    media = 'mean',
    mediana = 'median',
    variancia = 'var',
    desvio_padrao = 'std',
    mad = lambda x: np.mean(np.abs(x - x.mean()))
).reset_index()
estatisticas_operacional

O que podemos constatar aqui:
1. **Média e Mediana:** Ambos os cargos têm valores próximos, indicando simetria na centralidade.

2. **Variância e Desvio Padrão:** O cargo de Estoquista tem maior variância e desvio padrão, revelando maior dispersão nos salários.

3. **MAD vs. Desvio Padrão:** Em ambos os casos o MAD é menor em relação ao desvio padrão, indicando que a dispersão está sendo influenciada por valores extremos.


#### **Visualizando graficamente**

In [ ]:
plt.figure(figsize=(8, 6))
sns.violinplot(x='remuneracao', y='cargo', data=operacional)

plt.title('Distribuição de Salários por Cargo')
plt.xlabel('Salário (R$)')
plt.ylabel('Cargo')

plt.show()

Conseguimos observar os comportamentos dos salários entre os profissionais estoquistas e repositores e percebemos que ambos têm média e mediana salariais muito próximas, entretando notamos uma dispersão considerável entre os salários dos colaboradores, que foi comprovado tanto pelo desvio padrão e MAD quanto observando o intervalo interquartil (IIQ) no gráfico de violino.

Consideração para o RH:

* As métricas indicam que o cargo de Estoquista possui maior variabilidade salarial.
* O RH deve investigar se essa inconsistência reflete discrepâncias injustas ou se há justificativas baseadas em mérito ou experiência.

Como sugestão:
* Ajuste das políticas para reduzir a inconsistência salarial, promovendo equidade.
* Compartilhamento de mais informações para análise de outras métricas para maior robustez na análise.